/**
 * Build-time image generation. Resolves the palette into the SVG sources in
 * `scripts/assets/`, writes them to `public/`, and rasterises them into the PNG
 * variants referenced by BaseHead.astro, so no binaries live in git.
 *
 * Runs via `prebuild` and `predev`. It runs before dev as well as before build
 * because `public/favicon.svg` is served to the browser directly, so a stale or
 * missing one is visible in development and not just in a deploy.
 *
 * The generated SVGs stay tracked. They are what a fresh clone serves before
 * anything has been built, and keeping them in git means a palette change shows
 * up as a reviewable diff rather than as an invisible build artefact.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import sharp from 'sharp';
import { paletteFrom } from './tokens.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const publicDir = join(__dirname, '..', 'public');
const sourceDir = join(__dirname, 'assets');
const stylesheet = join(__dirname, '..', 'src', 'styles', 'global.css');

const OG_SIZE = { width: 1200, height: 630 };
/*
 * 16px gets its own artwork. Three letters at that size are five pixels each,
 * which no typeface survives, so the smallest icon is a single letter and
 * everything above it is the three-letter mark.
 */
const FAVICON_SIZES = [
  { file: 'favicon-32x32.png', size: 32 },
  { file: 'favicon-48x48.png', size: 48 },
  { file: 'favicon-512x512.png', size: 512 },
  { file: 'apple-touch-icon.png', size: 180 },
];

const BANNER = (source) =>
  `<!-- GENERATED by scripts/generate-og.mjs. Edit scripts/assets/${source}, not this file. -->\n`;

const palette = paletteFrom(await readFile(stylesheet, 'utf8'));

/**
 * Substitutes `{{token}}` for the palette value of that token. An unknown token
 * throws rather than being left in the output: a `{{accent}}` that silently
 * survives into a rasterised PNG is a black rectangle nobody notices until the
 * link preview is already out in the world.
 */
async function resolveSource(file, { publish = true } = {}) {
  const template = await readFile(join(sourceDir, file), 'utf8');
  const resolved = template.replace(/\{\{([a-z0-9-]+)\}\}/g, (_, token) => {
    const value = palette[token];
    if (!value) {
      throw new Error(
        `${file} references {{${token}}}, which is not a --rgb-* token in src/styles/global.css. ` +
          `Known tokens: ${Object.keys(palette).join(', ')}`,
      );
    }
    return value;
  });
  // Only the sources a browser actually requests are written to public/. The
  // 16px artwork is an input to the rasteriser and nothing else, so publishing
  // it would ship a file no one fetches.
  if (publish) {
    await writeFile(join(publicDir, file), BANNER(file) + resolved);
  }
  console.log(`${file} resolved${publish ? '' : ' (not published)'}`);
  return resolved;
}

async function render(svg, targetFile, { width, height }) {
  const png = await sharp(Buffer.from(svg)).resize(width, height).png({ quality: 90 }).toBuffer();
  await writeFile(join(publicDir, targetFile), png);
  console.log(`${targetFile} generated (${png.byteLength} bytes)`);
}

const og = await resolveSource('og.svg');
const favicon = await resolveSource('favicon.svg');
const faviconSmall = await resolveSource('favicon-small.svg', { publish: false });

await render(og, 'og.png', OG_SIZE);
await render(faviconSmall, 'favicon-16x16.png', { width: 16, height: 16 });

for (const { file, size } of FAVICON_SIZES) {
  await render(favicon, file, { width: size, height: size });
}
